# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 13:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(default='', upload_to='images/')),
                ('texto', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField(auto_now_add=True, db_index=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
