# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 14:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_noticia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
