# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('servicio', '0002_servicio_establecimiento'),
        ('animal', '0003_auto_20160801_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePalpacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.BooleanField()),
                ('gestacion', models.IntegerField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpaciones', to='animal.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Palpacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_manual', models.BooleanField(default=True)),
                ('fecha', models.DateField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpaciones', to='establecimiento.Establecimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpaciones', to='servicio.Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='detallepalpacion',
            name='palpacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='palpacion.Palpacion'),
        ),
    ]
