# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palpacion',
            name='metodo_manual',
        ),
        migrations.AddField(
            model_name='palpacion',
            name='metodo',
            field=models.CharField(choices=[('M', 'Manual'), ('E', 'Ecografo')], default='M', max_length=1),
        ),
    ]
