# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpacion', '0002_auto_20160812_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='palpacion',
            name='cantidad_prenados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palpacion',
            name='cantidad_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallepalpacion',
            name='gestacion',
            field=models.CharField(max_length=8),
        ),
    ]
