# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palpacion', '0003_auto_20160814_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepalpacion',
            name='gestacion',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
