# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('configuracion', '0001_initial'),
        ('establecimiento', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInseminacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminaciones', to='animal.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Inseminacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminaciones', to='establecimiento.Establecimiento')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminaciones', to='servicio.Servicio')),
            ],
        ),
        migrations.AddField(
            model_name='detalleinseminacion',
            name='inseminacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inseminacion.Inseminacion'),
        ),
        migrations.AddField(
            model_name='detalleinseminacion',
            name='pajuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inseminaciones', to='configuracion.Pajuela'),
        ),
    ]
