# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 19:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('E', 'Expirado'), ('B', 'Borrado')], default='A', max_length=1)),
                ('plan', models.CharField(choices=[('A', 'Activo'), ('E', 'Expirado'), ('B', 'Borrado')], default='G', max_length=1)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('departamento', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establecimiento', to='establecimiento.Departamento')),
                ('miembros', models.ManyToManyField(blank=True, related_name='establecimientos', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('leido', models.BooleanField(default=False)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea', to='establecimiento.Establecimiento')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_asignada', to=settings.AUTH_USER_MODEL)),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarea_creada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='establecimiento.Departamento'),
        ),
    ]
