# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('E', 'Expirado'), ('B', 'Borrado')], default='A', max_length=1)),
                ('fecha_expiracion', models.DateField()),
                ('miembros', models.ManyToManyField(blank=True, related_name='establecimientos', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
