# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
