# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='establecimientos', to=settings.AUTH_USER_MODEL),
        ),
    ]
