# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('A', 'Administrador'), ('C', 'Contador'), ('P', 'Propietario')], default='A', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='establecimiento',
            name='miembros',
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miembro',
            name='establecimeinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='establecimiento.Establecimiento'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to=settings.AUTH_USER_MODEL),
        ),
    ]
