# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='plan',
            field=models.CharField(choices=[('P', 'Premium'), ('E', 'Estandar'), ('G', 'Educativo')], default='G', max_length=1),
        ),
    ]
