# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_auto_20160503_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('E', 'Expirado')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='fecha_expiracion',
            field=models.DateField(default=datetime.datetime(2016, 5, 19, 20, 4, 30, 191830)),
        ),
    ]
