# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_miembro_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='cargo',
            field=models.CharField(choices=[('A', 'Administrador'), ('C', 'Contador'), ('P', 'Propietario'), ('V', 'Veterinario'), ('I', 'Ingeniero'), ('S', 'Secretario/a')], default='A', max_length=1),
        ),
    ]
