# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_auto_20160903_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='establecimeinto',
            new_name='establecimiento',
        ),
    ]
