# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0003_auto_20160903_1750'),
        ('establecimiento', '0002_auto_20160904_0918'),
    ]

    operations = [
    ]
