# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0003_auto_20160519_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='fecha_expiracion',
            field=models.DateField(),
        ),
    ]
