# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0004_auto_20160519_2005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='establecimiento',
            unique_together=set([('owner', 'nombre')]),
        ),
    ]
