# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0004_establecimiento_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 21, 1, 25, 30, 927999, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 21, 1, 25, 33, 186431, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 21, 1, 25, 35, 615886, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 21, 1, 25, 38, 290334, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
