# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0005_auto_20161020_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarea_asignada', to=settings.AUTH_USER_MODEL),
        ),
    ]
