# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0005_auto_20160519_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='establecimiento',
            unique_together=set([]),
        ),
    ]
