# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0006_auto_20160519_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('E', 'Expirado'), ('B', 'Borrado')], default='A', max_length=1),
        ),
    ]
