# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0006_auto_20161127_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
