# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0008_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='usuario',
            new_name='usuario_asignado',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarea_creada', to=settings.AUTH_USER_MODEL),
        ),
    ]
