# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(default=None, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('superficie', models.PositiveIntegerField(blank=True)),
                ('uso', models.TextField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potreros', to='establecimiento.Establecimiento')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='potrero',
            unique_together=set([('establecimiento', 'codigo')]),
        ),
    ]
