# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='codigo',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='superficie',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='potrero',
            unique_together=set([('establecimiento', 'codigo')]),
        ),
    ]
