# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrero', '0002_potrero_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potrero',
            name='superficie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potrero',
            name='uso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
