# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrero', '0003_auto_20170112_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='potrero',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
