# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='establecimiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='establecimiento.Establecimiento'),
        ),
        migrations.AddField(
            model_name='raza',
            name='establecimiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='establecimiento.Establecimiento'),
        ),
    ]
