# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 21, 1, 25, 10, 556956, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pajuela',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 21, 1, 25, 13, 35489, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raza',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 21, 1, 25, 15, 330019, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
