# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_auto_20160605_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='raza',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
