# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_raza_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='establecimiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='establecimiento.Establecimiento'),
        ),
    ]
