# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_auto_20160609_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(default='', max_length=20),
        ),
    ]
