# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0005_auto_20160614_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='establecimiento',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='establecimiento.Establecimiento'),
        ),
    ]
