# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0002_auto_20160503_0234'),
        ('potrero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('peso_promedio', models.FloatField(blank=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='establecimiento.Establecimiento')),
                ('potrero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='potrero.Potrero')),
            ],
        ),
    ]
