# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
        ('establecimiento', '0001_initial'),
        ('potrero', '0001_initial'),
        ('sanitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('V', 'Vendido'), ('N', 'Normal')], default='N', max_length=1)),
                ('nombre', models.CharField(max_length=80)),
                ('peso_promedio', models.FloatField(blank=True, null=True)),
                ('is_venta', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(default=0, editable=False)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='establecimiento.Establecimiento')),
                ('potrero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='potrero.Potrero')),
                ('vacunacion', models.ManyToManyField(blank=True, default=None, related_name='lotes', to='sanitacion.Vacunacion')),
                ('venta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='venta.Venta')),
            ],
        ),
    ]
