# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='peso_promedio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
