# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_auto_20160503_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='is_venta',
            field=models.BooleanField(default=False),
        ),
    ]
