# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_remove_venta_lote'),
        ('lote', '0003_lote_is_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='venta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='venta.Venta'),
        ),
    ]
