# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_lote_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('V', 'Vendido'), ('N', 'Normal')], default='N', max_length=1),
        ),
    ]
