# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('lote', '0005_lote_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='servicio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to='servicio.Servicio'),
        ),
    ]
