# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0008_vacunacion'),
        ('lote', '0006_lote_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='vacunacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones', to='sanitacion.Vacunacion'),
        ),
    ]
