# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_establecimiento'),
        ('lote', '0006_lote_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='servicio',
        ),
        migrations.AddField(
            model_name='lote',
            name='servicio',
            field=models.ManyToManyField(default=None, null=True, related_name='lotes', to='servicio.Servicio'),
        ),
    ]
