# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0007_auto_20160801_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='servicio',
            field=models.ManyToManyField(default=None, related_name='lotes', to='servicio.Servicio'),
        ),
    ]
