# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0009_auto_20160803_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='vacunacion',
            field=models.ManyToManyField(blank=True, default=None, related_name='lotes', to='sanitacion.Vacunacion'),
        ),
    ]
