# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0010_auto_20160808_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='potrero',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lote', to='potrero.Potrero'),
        ),
    ]
