# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(default='', max_length=80)),
                ('rubro', models.CharField(choices=[('GD', 'Gastos Directos'), ('GA', 'Gastos Administrativos'), ('IT', 'Impuestos y Tazas'), ('GC', 'Gastos de Comercializaci\xf3n'), ('GF', 'Gastos Financieros')], default='GD', max_length=2)),
                ('monto', models.IntegerField()),
                ('porcentaje', models.IntegerField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egreso', to='establecimiento.Establecimiento')),
            ],
        ),
    ]
