# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(),
        ),
    ]
