# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20160808_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='porcentaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
