# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('contabilidad', '0003_auto_20160810_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDescripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=80)),
                ('monto_des', models.IntegerField(default=0)),
                ('porcentaje', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos_directos', models.IntegerField(default=0)),
                ('gastos_administrativos', models.IntegerField(default=0)),
                ('impuestos', models.IntegerField(default=0)),
                ('gastos_comercializacion', models.IntegerField(default=0)),
                ('gastos_financieros', models.IntegerField(default=0)),
                ('mes', models.IntegerField()),
                ('anho', models.IntegerField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporte_rubro', to='establecimiento.Establecimiento')),
            ],
        ),
        migrations.RemoveField(
            model_name='egreso',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='reportedescripcion',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion', to='contabilidad.ReporteEgreso'),
        ),
    ]
