# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-13 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('contabilidad', '0005_auto_20160811_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoVario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(default='', max_length=80)),
                ('comprador', models.CharField(default='', max_length=80)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_vario', to='establecimiento.Establecimiento')),
            ],
        ),
        migrations.RemoveField(
            model_name='reportedescripcion',
            name='rubro',
        ),
        migrations.RemoveField(
            model_name='reporteegreso',
            name='establecimiento',
        ),
        migrations.DeleteModel(
            name='ReporteDescripcion',
        ),
        migrations.DeleteModel(
            name='ReporteEgreso',
        ),
    ]
