# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('contabilidad', '0006_auto_20160812_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comprador', models.CharField(default='', max_length=80)),
                ('cantidad', models.PositiveIntegerField()),
                ('categoria', models.CharField(max_length=80)),
                ('carimbo', models.PositiveIntegerField()),
                ('peso_promedio', models.FloatField(blank=True, null=True)),
                ('total', models.PositiveIntegerField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_venta', to='establecimiento.Establecimiento')),
            ],
        ),
        migrations.AlterField(
            model_name='egreso',
            name='monto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingresovario',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ingresovario',
            name='precio_unitario',
            field=models.PositiveIntegerField(),
        ),
    ]
