# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('lote', '0001_initial'),
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_establecimiento_vendedor', models.CharField(max_length=32)),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('numero_guia', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('precio_total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('carga_masiva', models.BooleanField(default=False)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='establecimiento.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carimbo', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('caravana_inicial', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_compra', to='configuracion.Categoria')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_compra', to='compra.Compra')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_compra', to='lote.Lote')),
                ('raza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_compra', to='configuracion.Raza')),
            ],
        ),
    ]
