# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_auto_20160503_0234'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='establecimiento.Establecimiento'),
            preserve_default=False,
        ),
    ]
