# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
