# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_carga_masiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_compra', to='lote.Lote'),
        ),
    ]
