# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_auto_20160517_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='caravana_inicial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_compra', to='configuracion.Categoria'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='raza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_compra', to='configuracion.Raza'),
        ),
    ]
