# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_auto_20160503_0505'),
        ('compra', '0005_auto_20160705_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='precio_total',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_compra', to='lote.Lote'),
        ),
    ]
