# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
        ('establecimiento', '0002_auto_20160503_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('V', 'Vivo'), ('M', 'Muerto'), ('E', 'Eliminado')], default='V', max_length=1)),
                ('caravana', models.CharField(max_length=8)),
                ('carimbo', models.PositiveIntegerField()),
                ('prenada', models.BooleanField(default=False)),
                ('estado_sanitario', models.CharField(choices=[('E', 'En fecha'), ('N', 'No esta en fecha'), ('D', 'Desconocido')], default='E', max_length=1)),
                ('peso_especifico', models.FloatField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='configuracion.Categoria')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='establecimiento.Establecimiento')),
            ],
        ),
    ]
