# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='venta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='venta.Venta'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('V', 'Vivo'), ('M', 'Muerto'), ('E', 'Eliminado'), ('V', 'Vendido')], default='V', max_length=1),
        ),
    ]
