# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0008_vacunacion'),
        ('animal', '0003_auto_20160801_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='vacunacion',
            field=models.ManyToManyField(blank=True, default=None, related_name='animales', to='sanitacion.Vacunacion'),
        ),
    ]
