# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_auto_20160503_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_hembra',
            field=models.BooleanField(default=False),
        ),
    ]
