# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_animal_is_hembra'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
