# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_establecimiento'),
        ('animal', '0004_animal_vacunacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='servicio',
            field=models.ManyToManyField(blank=True, default=None, related_name='toros', to='servicio.Servicio'),
        ),
    ]
