# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0009_auto_20160803_2127'),
        ('animal', '0004_animal_vacunacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='vacunacion',
        ),
        migrations.AddField(
            model_name='animal',
            name='vacunacion',
            field=models.ManyToManyField(default=None, null=True, related_name='animales', to='sanitacion.Vacunacion'),
        ),
    ]
