# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_animal_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='peso',
        ),
    ]
