# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_auto_20160803_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='vacunacion',
            field=models.ManyToManyField(blank=True, default=None, related_name='animales', to='sanitacion.Vacunacion'),
        ),
    ]
