# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
        ('animal', '0007_animal_mortandad'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='detalle_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='compra.DetalleCompra'),
        ),
        migrations.AddField(
            model_name='animal',
            name='origen',
            field=models.CharField(choices=[('C', 'Compra'), ('N', 'Nacimiento'), ('S', 'Carga de sistema')], default='S', max_length=1),
        ),
    ]
