# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0007_auto_20160523_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='detalle_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='compra.DetalleCompra'),
        ),
    ]
