# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0008_auto_20160517_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='caravana_madre',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
