# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lote', '0001_initial'),
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo', models.CharField(choices=[('N', 'Monta Natural'), ('I', 'Inseminacion Artificial')], default='N', max_length=1)),
                ('cantidad_toros', models.IntegerField(default=0)),
                ('palpado', models.BooleanField(default=False)),
                ('establecimiento', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='establecimiento.Establecimiento')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='lote.Lote')),
            ],
        ),
    ]
