# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='establecimiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='establecimiento.Establecimiento'),
        ),
    ]
