# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='cantidad_prenados',
            new_name='cantidad_toros',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='cantidad_total',
        ),
    ]
