# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0012_remove_lote_servicio'),
        ('servicio', '0002_servicio_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='lote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='lote.Lote'),
            preserve_default=False,
        ),
    ]
