# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_servicio_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cantidad_prenados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='cantidad_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
