# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_auto_20160812_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cantidad_prenados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cantidad_total',
            field=models.IntegerField(default=0),
        ),
    ]
