# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('lote', '0003_lote_is_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_establecimiento_comprador', models.CharField(max_length=32)),
                ('nombre_comprador', models.CharField(max_length=100)),
                ('numero_guia', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('precio_total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='establecimiento.Establecimiento')),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalle_venta', to='lote.Lote')),
            ],
        ),
    ]
