# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_remove_venta_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(default='lote', max_length=10),
        ),
    ]
