# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20160621_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ingreso_empresa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
