# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-13 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_auto_20161020_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratista',
            name='actualidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratista',
            name='salida_empresa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='actualidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salida_empresa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
