# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_auto_20160621_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='escaneo_cedula',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
    ]
