# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20160621_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='escaneo_cedula',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ingreso_empresa',
            field=models.DateTimeField(null=True),
        ),
    ]
