# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20160621_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='escaneo_cedula',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 4, 15, 20, 58, 550247, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ingreso_empresa',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 4, 15, 22, 36, 770442, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
