# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_auto_20160705_0959'),
        ('empleado', '0005_auto_20160704_1122'),
    ]

    operations = [
    ]
