# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ingreso_empresa',
            field=models.DateTimeField(null=True),
        ),
    ]
