# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0001_initial'),
        ('configuracion', '0006_auto_20160705_1145'),
        ('lote', '0002_auto_20160503_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGenetica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('nombre_corto', models.CharField(max_length=32)),
                ('porcentaje_pureza', models.PositiveIntegerField(choices=[('25', 25), ('50', 50), ('75', 75), ('100', 100)])),
                ('tipo_servicio', models.CharField(choices=[('Monta Natural', 'MN'), ('Inceminacion Artificial', 'IA')], max_length=2)),
                ('rp', models.CharField(max_length=32)),
                ('descripcion', models.TextField()),
                ('cantidad_pajuelas', models.PositiveIntegerField()),
                ('pedigree_padre', models.CharField(max_length=32)),
                ('pedigree_madre', models.CharField(max_length=32)),
                ('pedigree_abuelo', models.CharField(max_length=32)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animal.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='LoteGenetica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_pureza', models.PositiveIntegerField(choices=[('25', 25), ('50', 50), ('75', 75), ('100', 100)])),
                ('tipo_servicio', models.CharField(choices=[('Monta Natural', 'MN'), ('Inceminacion Artificial', 'IA')], max_length=2)),
                ('carimbo', models.PositiveIntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9)])),
                ('descripcion', models.TextField()),
                ('pedigree_padre', models.CharField(max_length=32)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Categoria')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lote.Lote')),
                ('raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Raza')),
            ],
        ),
    ]
