# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0007_auto_20160519_2134'),
        ('genetica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalgenetica',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animal_genetica', to='establecimiento.Establecimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotegenetica',
            name='establecimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lote_genetica', to='establecimiento.Establecimiento'),
            preserve_default=False,
        ),
    ]
