# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genetica', '0002_auto_20160815_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalgenetica',
            name='porcentaje_pureza',
            field=models.PositiveIntegerField(choices=[(25, '25'), (50, '50'), (75, '75'), (100, '100')]),
        ),
        migrations.AlterField(
            model_name='animalgenetica',
            name='tipo_servicio',
            field=models.CharField(choices=[('MN', 'Monta Natural'), ('IA', 'Inceminacion Artificial')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lotegenetica',
            name='carimbo',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]),
        ),
        migrations.AlterField(
            model_name='lotegenetica',
            name='porcentaje_pureza',
            field=models.PositiveIntegerField(choices=[(25, '25'), (50, '50'), (75, '75'), (100, '100')]),
        ),
        migrations.AlterField(
            model_name='lotegenetica',
            name='tipo_servicio',
            field=models.CharField(choices=[('MN', 'Monta Natural'), ('IA', 'Inceminacion Artificial')], max_length=2),
        ),
    ]
