# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genetica', '0005_animalgenetica_lote_genetica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalgenetica',
            name='lote_genetica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_genetica', to='genetica.LoteGenetica'),
        ),
    ]
