# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-12 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0002_auto_20161020_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoestablecimiento',
            name='veterinario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
