# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0002_auto_20160503_0234'),
        ('sanitacion', '0003_auto_20160517_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEstablecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('color', models.CharField(default='#CDDC39', max_length=7)),
                ('veterinario', models.TextField()),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='establecimiento.Establecimiento')),
            ],
        ),
    ]
