# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0004_eventoestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='allDay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoestablecimiento',
            name='allDay',
            field=models.BooleanField(default=True),
        ),
    ]
