# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0005_auto_20160517_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventoestablecimiento',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventoestablecimiento',
            name='start',
            field=models.DateField(),
        ),
    ]
