# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0008_vacunacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunacion',
            name='codigo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='enfermedad',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='veterinario',
            field=models.CharField(default='', max_length=40),
        ),
    ]
