# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitacion', '0009_auto_20160803_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunacion',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
